#!/bin/bash
EMSDK_PATH=/root/emsdk
EMSDK_VERSION=4.0.3
NODE_VERSION=22
BIN_PATH=/usr/local/bin

IMAGE_NAME="carta-appimage-create"
CONTAINER_NAME="carta-appimage-container"

PACKAGING_PATH=$(pwd)
DOCKER_PACKAGING_PATH=/pack

ARCH=arm64
BACKGROUND_FIGURE=""

# Can be branch, tag or commit
FRONTEND_VERSION=v5.0.2
BACKEND_VERSION=v5.0.1

RELEASE=FALSE

# Naming the output file if it is a release packaging (RELEASE=TRUE)
RELEASE_VERSION=5.0.0

NPM_FRONTEND=FALSE

# Set to TRUE if it is a beta release
BETA_RELEASE=FALSE

# Set to TRUE to update the measurement data
UPDATE_MEASURES_DATA=FALSE

PREPARE_FRONTEND=TRUE
PREPARE_BACKEND=TRUE

# Set to TRUE if it is a release packaging (RELEASE=TRUE)
CLEAN_FRONTEND=TRUE
CLEAN_BACKEND=TRUE