#!/bin/bash
EMSDK_PATH=/root/emsdk
EMSDK_VERSION=4.0.3
NODE_VERSION=22
BIN_PATH=/usr/local/bin

IMAGE_NAME="carta-appimage-create"
CONTAINER_NAME="carta-appimage-container"

PACKAGING_PATH=/home/pshnghng/carta-package/CARTA-AppImage-creator
DOCKER_PACKAGING_PATH=/pack

ARCH=arm64
BACKGROUND_FIGURE=""

# Can be branch, tag or commit
FRONTEND_VERSION=v6.0.0-beta.1
BACKEND_VERSION=v6.0.0-beta.1

RELEASE=TRUE

# Naming the output file if it is a release packaging (RELEASE=TRUE)
RELEASE_VERSION=v6.0.0-beta.1

NPM_FRONTEND=TRUE

# Set to TRUE if it is a beta release
BETA_RELEASE=TRUE

# Set to TRUE to update the measurement data
UPDATE_MEASURES_DATA=FALSE

PREPARE_FRONTEND=TRUE
PREPARE_BACKEND=TRUE

# Set to TRUE if it is a release packaging (RELEASE=TRUE)
CLEAN_FRONTEND=FALSE
CLEAN_BACKEND=FALSE

