# Dockerfile to build and package a universal Linux Appimage of CARTA.
# Built on our oldest supported platform (Almalinux8.10/RHEL7) to ensure full forward compatibility.
# Requires BASE_IMAGE, ARCH_TYPE, CASACORE_TAG, BACKEND_TAG, FRONTEND_TAG, and VERSION arguments from the 'create-carta-appimage.sh' script.

ARG BASE_IMAGE
# On x86_64 it uses "almalinux:8.10", on aarch64 it uses "arm64v8/almalinux:8.10"
FROM $BASE_IMAGE

ARG CASACORE

# Install the required packages
RUN \
    dnf -y install epel-release && \
    dnf -y install 'dnf-command(config-manager)' && \
    dnf -y config-manager --set-enabled powertools && \
    dnf -y update && \
    dnf -y install autoconf automake bison blas-devel bzip2 cmake curl-devel flex fftw fftw-devel gcc \
            gcc-c++ gcc-gfortran git git-lfs gsl-devel hdf5-devel lapack-devel libasan \
            libtool libxml2-devel libzstd-devel libuuid-devel make ncurses-devel openssl-devel patchelf protobuf-devel \
            pugixml-devel python3.12 python3.12-pip readline-devel subversion \
            unzip wcslib-devel wget zlib-devel libuuid-devel zfp-devel && \
    dnf install -y fuse fuse-libs squashfs-tools desktop-file-utils appstream file && \
    pip3 install --upgrade pip && \
    pip3 install numpy astropy

# Install cfitsio
RUN \
    source /etc/bashrc && \
    cd /root && \
    git clone --recursive https://github.com/HEASARC/cfitsio.git && \
    cd cfitsio/ && \
    autoreconf -f -i && \
    ./configure --prefix=/opt/cfitsio && \
    make && \
    make install && \
    cp /opt/cfitsio/lib/lib* /usr/lib64 && \
    rm -rf /root/cfitsio

# Get the latest geodetic and ephemerides measures data
RUN \
    source /etc/bashrc && \
    cd /root && \
    mkdir -p /usr/local/share/casacore/data && \
    wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar && \
    tar -xzf WSRT_Measures.ztar && \
    cp -r geodetic /usr/local/share/casacore/data && \
    cp -r ephemerides /usr/local/share/casacore/data && \
    rm -rf WSRT_Measures.ztar geodetic ephemerides

# Install fits2idia from the Copr cartavis/carta repository
RUN \
    dnf -y install 'dnf-command(copr)' && \
    dnf -y copr enable cartavis/carta && \
    dnf -y install fits2idia gmock-devel gtest-devel measures-data

# Get libsofa.a for casacore
RUN \
    source /etc/bashrc && \
    cd /root && \
    wget http://www.iausofa.org/2018_0130_F/sofa_f-20180130.tar.gz && \
    tar xzf sofa_f-20180130.tar.gz && rm sofa_f-20180130.tar.gz && \
    cd sofa/20180130/f77/src && make && cp libsofa.a /usr/lib/libsofa.a && \
    cd /root && rm -rf sofa

# Install carta-casacore from CARTAvis repo (with the floating CASAROOT)
RUN \
    source /etc/bashrc && \
    cd /root && \
    ls -sort && \
    git clone --recursive https://github.com/CARTAvis/carta-casacore.git && \
    cd carta-casacore && \
    git checkout ${CASACORE} && \
    git submodule update --init --recursive && \
    mkdir -p build && cd build && \
    cmake .. -DUSE_FFTW3=ON \
            -DUSE_HDF5=ON \
            -DUSE_THREADS=ON \
            -DUSE_OPENMP=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=OFF \
            -DBUILD_PYTHON=OFF \
            -DUseCcache=1 \
            -DHAS_CXX11=1 \
            -DDATA_DIR="%CASAROOT%/data" \
            -DCMAKE_INSTALL_PREFIX=/opt/carta-casacore \
            -DENABLE_RPATH=NO \
            -DCMAKE_PREFIX_PATH=/opt/cfitsio && \
    make -j 4 && make install && \
    cd /root && rm -rf carta-casacore && \
    echo "/opt/carta-casacore/lib" >> /etc/ld.so.conf.d/carta-casacore.conf

RUN \
    cd /root && \
    git clone https://github.com/emscripten-core/emsdk.git && \
    cd emsdk && \
    git pull


RUN \
    mkdir -p /pack/CARTA && \
    mkdir -p /pack/CARTA/usr/share/metainfo