# Dockerfile to build and package a universal Linux Appimage of CARTA.
# Built on our oldest supported platform (CentOS7.9/RHEL7) to ensure full forward compatibility.
# Requires BASE_IMAGE, ARCH_TYPE, CASACORE_TAG, BACKEND_TAG, FRONTEND_TAG, and VERSION arguments from the 'create-carta-appimage.sh' script.

ARG BASE_IMAGE
# On x86_64 it uses "centos:7.9.2009", on aarch64 it uses "arm64v8/centos:7.9.2009"
FROM $BASE_IMAGE

ARG ARCH_TYPE
ARG CASACORE
ARG NPM
ARG FRONTEND
ARG BACKEND
ARG RELEASE_TAG
ARG APPIMAGE_VER

# The carta-backend will use GCC 8 functions, so install and activate devtoolset-8 
RUN \
  yum -y install centos-release-scl && \
  yum install -y centos-release-scl && yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-gcc-gfortran && \
  echo "source scl_source enable devtoolset-8" >> /etc/bashrc

# Install the required packages
RUN \
  yum -y install yum-plugin-copr && \
  yum -y copr enable cartavis/carta && \
  yum -y install epel-release && \
  yum install -y autoconf automake bison carta-gsl-devel blas-devel bzip2 cfitsio-devel curl-devel cmake3 flex \
    git git-lfs gtest-devel hdf5-devel lapack-devel libtool libxml2-devel libzstd-devel \
    make openssl-devel protobuf-devel pugixml-devel readline-devel subversion systemd-devel wcslib-devel wget \
    zlib-devel libuuid-devel patchelf file zfp-devel && \
  ln -s /usr/bin/cmake3 /usr/bin/cmake

# We use some custom RPMs that we host of Fedora Copr, Unfortunately Fedora Copr does not support el7 aarch64.
# So we now included the aarch64 carta-gsl, protobuf, and zfp RPMs in the aarch64-RPM folder and install them on aarch64 only..
COPY aarch64-RPMs/* /aarch64-RPMs/
RUN if [ "$ARCH_TYPE" = "aarch64" ]; then \
        yum -y remove protobuf protobuf-devel && \
        yum -y localinstall /aarch64-RPMs/*.rpm; \
    fi

# Get the latest geodetic and ephemerides measures data
RUN \
  source /etc/bashrc && \
  mkdir -p /usr/local/share/casacore/data/geodetic/Observatories && \
  cd /root && \
  wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar && \
  tar -xzf WSRT_Measures.ztar && \
  cp -r geodetic/Observatories/* /usr/local/share/casacore/data/geodetic/Observatories/

# Get libsofa.a for casacore
RUN \
  source /etc/bashrc && \
  wget http://www.iausofa.org/2018_0130_F/sofa_f-20180130.tar.gz && \
  tar xzf sofa_f-20180130.tar.gz && rm sofa_f-20180130.tar.gz && \
  cd sofa/20180130/f77/src && make && cp libsofa.a /usr/lib/libsofa.a && \
  cd /root && rm -rf sofa

# Install carta-casacore from CARTAvis repo (with the floating CASAROOT)
RUN \
  source /etc/bashrc && \
  cd /root && \
  ls -sort && \
  git clone https://github.com/CARTAvis/carta-casacore.git && \
  cd carta-casacore && \
  git checkout ${CASACORE} && \
  git submodule init && git submodule update && \
  cd casa6 && \
  git submodule init && git submodule update && \
  cd ../ && mkdir -p build && cd build && \
  cmake .. -DUSE_FFTW3=ON \
           -DUSE_HDF5=ON \
           -DUSE_THREADS=ON \
           -DUSE_OPENMP=ON \
           -DCMAKE_BUILD_TYPE=Release \
           -DBUILD_TESTING=OFF \
           -DBUILD_PYTHON=OFF \
           -DUseCcache=1 \
           -DHAS_CXX11=1 \
           -DDATA_DIR="%CASAROOT%/data" \
           -DCMAKE_INSTALL_PREFIX=/opt/carta-casacore \
           -DENABLE_RPATH=NO \
           -DGSL_CONFIG=/opt/carta-gsl/bin/gsl-config \
           -DGSL_INCLUDE=/opt/carta-gsl/include \
           -DGSL_LIBRARY_PATH=/opt/carta-gsl/lib \
           -DGSL_CONFIG=/opt/carta-gsl/bin/gsl-config \
           -DCMAKE_CXX_FLAGS="-I/opt/carta-gsl/include" \
           -DCMAKE_CXX_STANDARD_LIBRARIES="-L/opt/carta-gsl/lib" && \
  make -j4 && make install && \
  cd /root && rm -rf carta-casacore && \
  echo "/opt/carta-casacore/lib" >> /etc/ld.so.conf.d/carta-casacore.conf && \
  echo "/opt/carta-gsl/lib" >> /etc/ld.so.conf.d/carta-casacore.conf

# Prepare the carta-backend
# Adjust 'CMAKE_BUILD_TYPE' and 'CartaUserFolderPrefix' flags accordingly.
# Parallel 'make' needs a lot of RAM. If you get this error "c++: fatal error: Killed signal terminated program cc1plus" 
# assign more RAM to Docker. 4GB should be enough for make -j 2.
RUN \
  source /etc/bashrc && \
  cd /root && \
  git clone https://github.com/CARTAvis/carta-backend.git && \
  cd carta-backend && \
  git checkout ${BACKEND} && \
  git submodule update --init --recursive && \
  mkdir build && cd build && \
  cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo \
           -DCartaUserFolderPrefix=".carta-beta" \
           -DGSL_INCLUDE_DIR=/opt/carta-gsl/include \
           -DGSL_LIBRARY=/opt/carta-gsl/lib \
           -DGSL_CBLAS_LIBRARY=/opt/carta-gsl/lib \
           -DCMAKE_CXX_FLAGS="-I/opt/carta-gsl/include" \
           -DCMAKE_CXX_STANDARD_LIBRARIES="-L/opt/carta-gsl/lib" && \
  make -j 4

# Prepare the carta-frontend
# Either copy in the production frontend build in the create-carta-appimage.sh script
# OR Download the prebuilt version from npm (It will remove the folder the COPY command copies in from outside)
COPY carta-frontend/build /root/package/build

RUN \
  if [ "$NPM" = "True" ] ; then \
    source /etc/bashrc && \
    cd /root && \
    rm -rf /root/package && \
    wget https://registry.npmjs.org/carta-frontend/-/carta-frontend-$FRONTEND.tgz && \
    tar -xvf carta-frontend-${FRONTEND}.tgz && \
    yum -y install curl npm && \
    curl -O  $(npm view carta-frontend@dev dist.tarball | head -n 1) && \
    tar -xvf carta-frontend-$FRONTEND.tgz ; \
  fi

# Run patchelf on carta_backend executble and copy all required dependencies to the bundled lib folder
RUN \
  source /etc/bashrc && \
  mkdir -p /root/CARTA/bin && \
  cp /root/carta-backend/build/carta_backend /root/CARTA/bin && \
  patchelf --set-rpath "\$ORIGIN/lib" /root/CARTA/bin/carta_backend && \
  mkdir -p /root/CARTA/lib && \
  cp /usr/lib64/libaec.so.0 /root/CARTA/lib && \
  cp /usr/lib64/libblas.so.3 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_casa.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_coordinates.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_fits.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_imageanalysis.so.3 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_images.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_lattices.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_measures.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_mirlib.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_scimath.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_scimath_f.so.6 /root/CARTA/lib && \
  cp /opt/carta-casacore/lib/libcasa_tables.so.6 /root/CARTA/lib && \
  cp /usr/lib64/libcfitsio.so.2 /root/CARTA/lib && \
  cp /usr/lib64/libgfortran.so.3 /root/CARTA/lib && \
  cp /usr/lib64/libgfortran.so.5 /root/CARTA/lib && \
  cp /usr/lib64/libgomp.so.1 /root/CARTA/lib && \
  cp /opt/carta-gsl/lib/libgsl.so.23 /root/CARTA/lib && \
  cp /opt/carta-gsl/lib/libgslcblas.so.0 /root/CARTA/lib && \
  cp /usr/lib64/libhdf5.so.8 /root/CARTA/lib && \
  cp /usr/lib64/libhdf5_cpp.so.8 /root/CARTA/lib && \
  cp /usr/lib64/libhdf5_hl.so.8 /root/CARTA/lib && \
  cp /usr/lib64/liblapack.so.3 /root/CARTA/lib && \
  cp /usr/lib64/libncurses.so.5  /root/CARTA/lib && \
  cp /usr/lib64/libprotobuf.so.16 /root/CARTA/lib && \
  cp /usr/lib64/libpugixml.so.1 /root/CARTA/lib && \
  cp /usr/lib64/libreadline.so.6 /root/CARTA/lib && \
  cp /usr/lib64/libsz.so.2 /root/CARTA/lib && \
  cp /usr/lib64/libtinfo.so.5 /root/CARTA/lib && \
  cp /usr/lib64/libwcs.so.4 /root/CARTA/lib && \
  cp /usr/lib64/libzfp.so.0 /root/CARTA/lib && \
  cp /usr/lib64/libzstd.so.1 /root/CARTA/lib && \
  if [ "$ARCH_TYPE" = "x86_64" ]; then cp /usr/lib64/libquadmath.so.0 /root/CARTA/lib; fi

# Prepare the AppImage
RUN \
  source /etc/bashrc && \
  cp /opt/carta-casacore/bin/casa_data_autoupdate /root/CARTA/bin && \
  mkdir -p /root/CARTA/etc && \
  cp -r /usr/local/share/casacore/data /root/CARTA/etc && \
  mkdir -p /root/CARTA/share/carta/frontend && \
  cp -r /root/package/build/* /root/CARTA/share/carta/frontend/ && \
  mkdir -p /root/CARTA/usr/share/icons/hicolor/256x256/apps && \
  mkdir -p /root/CARTA/usr/share/icons/hicolor/128x128/apps && \
  cp -r /root/carta-backend/static/icons/256x256/cartaviewer.png /root/CARTA/usr/share/icons/hicolor/256x256/apps/ && \
  cp -r /root/carta-backend/static/icons/128x128/cartaviewer.png /root/CARTA/usr/share/icons/hicolor/128x128/apps/ && \
  mkdir -p /root/CARTA/usr/share/metainfo

COPY AppRun /root/CARTA
COPY carta.desktop /root/CARTA
COPY carta.png /root/CARTA
COPY org.carta.desktop.appdata.xml /root/CARTA/usr/share/metainfo

# Generate the AppImage
RUN \ 
  source /etc/bashrc && \
  cd /root && \
  mkdir -p /root/appimage && \
  wget https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-${APPIMAGE_VER}-${ARCH_TYPE}.AppImage && \
  chmod 755 appimagetool-${APPIMAGE_VER}-${ARCH_TYPE}.AppImage && \
  cd /root/CARTA && git init && \
  cd /root && \
  APPIMAGE_EXTRACT_AND_RUN=1 ARCH=${ARCH_TYPE} VERSION=${RELEASE_TAG} /root/appimagetool-${APPIMAGE_VER}-${ARCH_TYPE}.AppImage CARTA && \
  mv *.AppImage appimage

