#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
export CASAPATH="../../../../$DIR/etc linux"
export LD_LIBRARY_PATH=$DIR/lib:$LD_LIBRARY_PATH

for arg in "$@"
do
  $DIR/bin/carta_backend $@
done

if [ $# -eq 0 ]; then
  $DIR/bin/carta_backend
fi

